{% set name = "trx-python" %}
{% set version = "0.4.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 264e25d57dd98ead71a009a2e35a8143c98ff5b32fcabce7464a9d1a8c88195d

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - wheel
    - setuptools-scm >=7
    - pip
  run:
    - python >={{ python_min }}
    - deepdiff
    - nibabel >=5
    - numpy >=1.22
    - typer >=0.9

test:
  imports:
    - trx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tee-ar-ex/trx-python
  summary: Experiments with new file format for tractography
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - arokem
    - skoudoro
